### ISSUE TITLE
Tv app repo crash

### ISSUE THREAD

**Issue by Cahillsr** [ITVlab/TvAppRepo#47]
I have Xiaomi Mi Box Android 6.0
I have installed your app from the play Store. It seems to be just what I was looking for. But I have a problem. The problem I am having it the app crashes every time I try to create a shortcut

**Comment by Fleker** [comment]
That's unusual. Did you give the app storage access?

I'll check the crash logs soon and update this issue.

On Mar 22, 2017 8:55 AM, "Cahillsr" <notifications@github.com> wrote:

I have Xiaomi Mi Box Android 6.0
I have installed your app from the play Store. It seems to be just what I
was looking for. But I have a problem. The problem I am having it the app
crashes every time I try to create a shortcut

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ITVlab/TvAppRepo/issues/47>, or mute the thread

**Comment by Cahillsr** [comment]
Yes i did Tryed it in 3 different mi boxes all do the same


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Nick <notifications@github.com> Date: 3/22/17  11:32 AM  (GMT-05:00) To: ITVlab/TvAppRepo <TvAppRepo@noreply.github.com> Cc: Cahillsr <robertcahillsr@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ITVlab/TvAppRepo] Tv app repo crash (#47) 
That's unusual. Did you give the app storage access?



I'll check the crash logs soon and update this issue.



On Mar 22, 2017 8:55 AM, "Cahillsr" <notifications@github.com> wrote:



I have Xiaomi Mi Box Android 6.0

I have installed your app from the play Store. It seems to be just what I

was looking for. But I have a problem. The problem I am having it the app

crashes every time I try to create a shortcut



—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub

<https://github.com/ITVlab/TvAppRepo/issues/47>, or mute the thread

**Comment by Cahillsr** [comment]
I did not send report. Just Tryed again and same problem. Sent report from email address brianfallon1257@gmail.com


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Nick <notifications@github.com> Date: 3/22/17  11:32 AM  (GMT-05:00) To: ITVlab/TvAppRepo <TvAppRepo@noreply.github.com> Cc: Cahillsr <robertcahillsr@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ITVlab/TvAppRepo] Tv app repo crash (#47) 
That's unusual. Did you give the app storage access?



I'll check the crash logs soon and update this issue.



On Mar 22, 2017 8:55 AM, "Cahillsr" <notifications@github.com> wrote:



I have Xiaomi Mi Box Android 6.0

I have installed your app from the play Store. It seems to be just what I

was looking for. But I have a problem. The problem I am having it the app

crashes every time I try to create a shortcut



—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub

<https://github.com/ITVlab/TvAppRepo/issues/47>, or mute the thread

**Comment by Fleker** [comment]
I have an integrated crash report tool that doesn't need you to send the
report manually.

**Comment by Fleker** [comment]
Fixed

**Comment by Cahillsr** [comment]
Working great thank you
