### ISSUE TITLE
Enforce PNGs

### ISSUE THREAD

**Issue by Fleker** [ITVlab/TvAppRepo#5]
If the banner or icon is not a PNG, issue an error and stop the process. This is causing the build process to fail down the line because I'm downloading a JPG but saying it's a PNG.

**Comment by Xstar97** [comment]
this was never closed...so just offering more advice.

create a public static boolean method to check the image file extension before its being uploaded or downloaded & if it returns true then continue on in the process..however if it returns false...issue a toast or dialog message stating its the wrong file...but...if the file can be converted beforehand I think that would be a better option.
such as: very rough example & can be better
(i would suggest to use an asynctask)
public static void convert2PNG(filename){
try {
   FileOutputStream out = new FileOutputStream(filename);
   bmp.compress(Bitmap.CompressFormat.PNG, 100, out); //100-best quality
   out.close();
} catch (Exception e) {
   e.printStackTrace();
}
}
//is image a png?
public static boolean isPNG(File file/String string){
File f = new File(file);
String s = string;
String ext = f.getAbsolutePath().substring(f.getAbsolutePath().lastIndexOf("."));
//or
String ext = s.substring(ff.getAbsolutePath().lastIndexOf("."));

if(ext.equalsIgnoreCase("png"){
return true;
}else{
return false;
}
if a service downloaded a non-png image for banners/logos then you should convert the images to make it easier for your users & speed up the process even further.

**Comment by Fleker** [comment]
This was meant more for my own generating mechanism. Since we've moved away from that, this can be closed without fix
