### ISSUE TITLE
FX File Explorer/Build failed

### ISSUE THREAD

**Issue by 20mxm** [ITVlab/TvAppRepo#55]
Hi,
when I try to create a shortcut for FX File Explorer, I get Build failed.
Thanks﻿

**Comment by 20mxm** [comment]
Hi,
Any plans to fix FX File Explorer  Build failed error?

Thanks

**Comment by Fleker** [comment]
I think I will need to add some instrumentation tests that will check that every possible configuration will be valid.

**Comment by 20mxm** [comment]
Thank you!!! 
btw great app

**Comment by 20mxm** [comment]
Hi,
Any closer to a fix?

Thanks

**Comment by Fleker** [comment]
I've been away for the holidays, so I haven't had the chance to look into this yet.

**Comment by 20mxm** [comment]
Sorry, please forgive me. I didn't know.
I hope you had a good holiday!!!

**Comment by 20mxm** [comment]
Hi,
Any closer to a fix?

Thanks

**Comment by Fleker** [comment]
The good news is that instrumentation tests have been written and all the test cases pass. The bad news means I don't know why there's a problem with this specific app.

**Comment by Blurayx** [comment]
Hi Fleker,
Thanks for trying to fix it.

**Comment by Blurayx** [comment]
Hi Fleker,
Because this issue is still open, Are you hoping one day you will be able to fix it?

**Comment by Fleker** [comment]
Right now I'm not sure what the problem is. The tests are passing, so it's not a problem in the app or the server.

**Comment by Blurayx** [comment]
Out of all the file managers, Fx is my favourite for the Shield TV. I’m hoping one day it will work 

Thanks for the update

**Comment by Blurayx** [comment]
Update:
I created a home screen icon on my shield TV using  Android TV App Launcher Builder 
http://atvlauncher.trekgonewild.de/index.php
I'm getting an error, if I try to launch it. do you what it could be?
<a href="https://imgur.com/kjWuRNU"><img src="https://i.imgur.com/kjWuRNU.png" title="source: imgur.com" /></a>

I hope this info may shed some light on the issue.

**Comment by Fleker** [comment]
What did you use as the package name? It looks like you used a bad package name, using the Play Store link instead.

**Comment by 20mxm** [comment]
I used FX File Explore

configurations:
<a href="https://imgur.com/ztMX4Oc"><img src="https://i.imgur.com/ztMX4Oc.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/S1v2kVt"><img src="https://i.imgur.com/S1v2kVt.jpg" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
FX File Explorer working on my Home screen!!!

I followed the youtube instructions: https://www.youtube.com/watch?v=mOpUlfkhwc8

<a href="https://imgur.com/FwSSGGT"><img src="https://i.imgur.com/FwSSGGT.png" title="source: imgur.com" /></a>
